/*
 * TorreDeHanoi.java
 *
 * Created on 27 de Setembro de 2005, 03:30
 */

package martes.lairjunior.usjt.algesd.hanoi.gui;

import martes.lairjunior.usjt.algesd.hanoi.HanoiTowerControl;

/**
 *
 * @author  lair
 */
public class TorreDeHanoi extends javax.swing.JFrame {
    
    /** Creates new form TorreDeHanoi */
    public TorreDeHanoi() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        _painelJogo = new javax.swing.JPanel();
        _painelDePinosGui = new martes.lairjunior.usjt.algesd.hanoi.gui.PainelDePinosGui();
        _painelInicioJogo = new javax.swing.JPanel();
        _botaoIniciarJogo = new javax.swing.JButton();
        _quantidadeDiscosGuiCaixaDeTexto = new javax.swing.JTextField();
        _quantidadeDiscosGuiLabel = new javax.swing.JLabel();
        _botaoSair = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Torre de Hanoi - desenvolvido por Lair Martes Junior");
        _painelJogo.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        _painelJogo.add(_painelDePinosGui, gridBagConstraints);

        _painelInicioJogo.setLayout(new java.awt.GridBagLayout());

        _botaoIniciarJogo.setText("Iniciar Jogo");
        _botaoIniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _botaoIniciarJogoActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 3, 4);
        _painelInicioJogo.add(_botaoIniciarJogo, gridBagConstraints);

        _quantidadeDiscosGuiCaixaDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _quantidadeDiscosGuiCaixaDeTextoActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 3, 4);
        _painelInicioJogo.add(_quantidadeDiscosGuiCaixaDeTexto, gridBagConstraints);

        _quantidadeDiscosGuiLabel.setText("Quantidade de Discos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 3, 4);
        _painelInicioJogo.add(_quantidadeDiscosGuiLabel, gridBagConstraints);

        _botaoSair.setText("Sair");
        _botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _botaoSairActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 3, 4);
        _painelInicioJogo.add(_botaoSair, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        _painelJogo.add(_painelInicioJogo, gridBagConstraints);

        getContentPane().add(_painelJogo);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void _botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event__botaoSairActionPerformed

    private void _quantidadeDiscosGuiCaixaDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__quantidadeDiscosGuiCaixaDeTextoActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event__quantidadeDiscosGuiCaixaDeTextoActionPerformed

    private void _botaoIniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__botaoIniciarJogoActionPerformed
        int quantidadeDeDiscos = 0;
        try {
            quantidadeDeDiscos = Integer.parseInt(_quantidadeDiscosGuiCaixaDeTexto.getText());
        }catch (NumberFormatException e) {
            quantidadeDeDiscos = HanoiTowerControl.INITIAL_DISK_CAPACITY;
            _quantidadeDiscosGuiCaixaDeTexto.setText(Integer.toString(quantidadeDeDiscos));
        }
        HanoiTowerControl.getInstance().setQuantidadeDeDiscos(quantidadeDeDiscos);
        HanoiTowerControl.getInstance().iniciarJogo();
        _painelDePinosGui.iniciarJogo();
    }//GEN-LAST:event__botaoIniciarJogoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TorreDeHanoi().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _botaoIniciarJogo;
    private javax.swing.JButton _botaoSair;
    private martes.lairjunior.usjt.algesd.hanoi.gui.PainelDePinosGui _painelDePinosGui;
    private javax.swing.JPanel _painelInicioJogo;
    private javax.swing.JPanel _painelJogo;
    private javax.swing.JTextField _quantidadeDiscosGuiCaixaDeTexto;
    private javax.swing.JLabel _quantidadeDiscosGuiLabel;
    // End of variables declaration//GEN-END:variables
    
}
