/*
 * PinoVisualPanel.java
 *
 * Created on 27 de Setembro de 2005, 02:32
 *
 */

package game.ui.gui;

import com.martialdev.game.hanoitower.core.control.Pin;
import com.martialdev.game.hanoitower.core.control.Disk;

public class PinoVisualPanel extends javax.swing.JPanel {
    /** Creates new form PinoVisualPanel */
    public PinoVisualPanel() {
        initComponents();
        //testar();
    }
    public void setPino(Pin pino) {
        Object[] discos = pino.getDisks();
        int quantidade = (discos == null ? 0 : discos.length);
        String textoVisualPilha = "";
        for (int i = quantidade-1; i>=0; i--) {
            LinhaDeDisco linhaDesenhada = new LinhaDeDisco((Disk)discos[i]);
            textoVisualPilha += System.getProperty("line.separator") + linhaDesenhada;
        }
        _discoVisualTextPane.setText(textoVisualPilha);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        _discoVisualTextPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        _discoVisualTextPane.setEditable(false);
        _discoVisualTextPane.setFont(new java.awt.Font("Courier New", 1, 14));
        add(_discoVisualTextPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane _discoVisualTextPane;
    // End of variables declaration//GEN-END:variables
    
}
